### ISSUE TITLE
.Day template variable not working

### ISSUE THREAD

**Issue by jessesquires** [lowply/issue-from-template#12]
Hello! 👋🏼 

When I try to use the `{{ .Day }}` template variable, my workflow fails:

```
executing "body" at <.Day>: can't evaluate field Day in type *main.date
```

I've also tried `{{ . WeekStartDate }}` which **does** work.

**Comment by lowply** [comment]
@jessesquires Hi 👋🏻 Apologies for the delay in getting back to you!

What does your issue template look like? I've used the following issue template and it works fine:

```
---
name: Test
about: This is a test for issue #12
title: 'This is a test for issue #12'
labels: report
---

WeekNumber {{ .WeekNumber }}
WeekNumberYear {{ .WeekNumberYear }}
WeekStartDate {{ .WeekStartDate }}
Day {{ .Day }}
```

btw, if you have installed Go in your workstation, you can run this action locally by following https://github.com/lowply/issue-from-template#running-locally-for-development. If you get a chance, please do so against a test repository and share the full output with me.

Thank you!

**Comment by jessesquires** [comment]
Hey @lowply 

The failure was happening when using the variable for the title:

```markdown
title: 'Meeting {{ .Day }} {{ .Month }}'
```

**Comment by lowply** [comment]
@jessesquires thanks for confirming! I've tried using the variables in the `title`:

```
---
name: Test
about: This is a test for issue #12
title: 'Meeting {{ .Day }} {{ .Month }}'
labels: 'test'
---

Test
```

It went well:

```
Posting https://api.github.com/repos/[org]/[repo]/issues ...
Done!
{"title":"Meeting 27 04","body":"Test\n","assignees":[""],"labels":["test"]}
```

Would you be able to share the full template file that reproduces the issue with me?

**Comment by jessesquires** [comment]
Oh interesting. 

I've since moved on to using another similar action since opening this, so I'm entirely sure what the original template was. 

Sorry 😕

**Comment by lowply** [comment]
No worries, please let me know if you start using this action again in the future and experience the same issue. I'm closing this now, but thank you so much for reporting!
